### ISSUE TITLE
pls

### ISSUE THREAD

**Issue by Pomik108** [IsaiahPatton/fps-boost#1]
this is fake it's just inflating the fps counter

**Comment by IsaiahPatton** [comment]
No it is not. The vanilla game does the same thing, I just improved the calculation.

**Comment by npgoalkeeper** [comment]
I mean if you count cloning and displaying the last frame as fps boosting then sure, its a fps improvement mod.

Also multithreading isnt a good idea in OGL, though I doubt you could touch rendering to that extent without clashing with another mod
